version: "3"
services:
  web:
    build: ./
    ports:
      - "8181:80"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=BasicCRUD
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
volumes:
  db-data: